---
title: "class3"
author: "Yongran Yan"
date: "2023-03-18"
output:
  pdf_document: default
  html_document: default
---

```{r}
# to load libraries
library(gapminder)
library(ggplot2)
library(socviz)
library(tidyverse)

# to plot the trajectory of GDP over time for each country
p <- ggplot(data = gapminder, 
            mapping = aes(x = year, y = gdpPercap))

# use group aesthetic
p + geom_line(aes(group = country))
```

To facet the data (break into multiple plots)
```{r}
# to facet the plot above
p <- ggplot(data = gapminder, 
            mapping = aes(x = year, y = gdpPercap))

p + geom_line(aes(group = country)) + facet_wrap(~continent)
```

Improving the plot
```{r, message=FALSE}
p <- ggplot(data = gapminder, 
            mapping = aes(x = year, y = gdpPercap))

p + geom_line(color = 'gray70', aes(group = country)) +
  geom_smooth(size = 1.1, method = 'loess', se = FALSE) +
  scale_y_log10(labels = scales::dollar) +
  facet_wrap(~continent, ncol = 5) +
  labs(x = 'Year',
       y = 'GDP per capita',
       Title = 'GDP per capita on Five Continents')
```

Using facet_grid()
```{r, message=FALSE}
# to work with another data set using facet_grid()
p <- ggplot(data = gss_sm, mapping = aes(x= age, y = childs))

p + geom_point(alpha = 0.2) + geom_smooth() + facet_grid(sex~race)
```

look at the stat_ functions
```{r, message=FALSE}
p <- ggplot(data = gss_sm, mapping = aes(x = bigregion))

p + geom_bar()

# to use a non-default stat_
p <- ggplot(data = gss_sm, mapping = aes(x = bigregion))

p + geom_bar(mapping = aes(y = ..prop..)) # all the bars sum up to 100%

# to use the whole data set as one group
p <- ggplot(data = gss_sm, mapping = aes(x = bigregion))

p + geom_bar(mapping = aes(y = ..prop.., group = 1))
```
```{r}
# to set up a new bar plot
p <- ggplot(data = gss_sm, mapping = aes(x = bigregion, fill = religion))

p + geom_bar(position = 'fill')

# to facet the plot
p <- ggplot(data = gss_sm, mapping = aes(x = religion))

p + geom_bar(position = 'dodge', mapping = aes(y = ..prop.., group = 1)) +
  facet_wrap(~bigregion, ncol = 1)
```

Histogram
```{r}
p <- ggplot(data = midwest, mapping = aes(x = area))

p + geom_histogram(bins = 10)
```

Compare distributions in histograms
```{r}
# to subset the data set 
oh_wi <- c('OH', 'WI')

# to plot the subset of data in histogram
p <- ggplot(data = subset(midwest, subset = state %in% oh_wi), mapping = aes(x=percollege, fill=state))

p + geom_histogram(alpha=0.4, bins=20)
```

Density plots
```{r}
# to make a density plot
p <- ggplot(data = midwest, mapping = aes(x=area))

p + geom_density()

# to change color and transparency of the density plot
oh_wi <- c('OH', 'WI')

p <- ggplot(data = subset(midwest, subset = state %in% oh_wi), 
            mapping = aes(x = area, fill = state, color = state))

p + geom_density(alpha = 0.3)
```

Use the organdata
```{r}
organdata |>
  select(1:6) |>
  sample_n(size = 5)
```

```{r, message=FALSE}
# to plot the donor and years by countries
p <- ggplot(data = organdata, mapping = aes(x = year, y = donors))

p + geom_line(aes(group = country)) + facet_wrap(~country)
```

Geom_boxplot()
```{r}
p <- ggplot(data = organdata, mapping = aes(x=country, y=donors))

p + geom_boxplot()
```
```{r}
# one way of making the country names more visible
p <- ggplot(data = organdata, mapping = aes(x=country, y=donors))

p + geom_boxplot() + coord_flip()
```

```{r}
# to reorder the variable
# to order the country based on number of donors
p <- ggplot(data = organdata, mapping = aes(x = reorder(country, donors, na.rm =TRUE), y=donors))

p + geom_boxplot() + coord_flip()
```

```{r}
# to use geom_jitter
p <- ggplot(data = organdata, mapping = aes(x = reorder(country, donors, na.rm =TRUE), y=donors))
p + geom_jitter() + coord_flip()
```

```{r}
# process data with pipeline
by_country <- organdata |> 
  group_by(consent_law, country) |> 
  summarize_if(is.numeric, funs(mean, sd), na.rm = TRUE) |> 
  ungroup()

# to make a cleveland dotplot
p <- ggplot(by_country, mapping = aes(x=donors_mean,
                                      y=reorder(country, donors_mean), color=consent_law))

p + geom_point(size=3) + labs(x = 'Donor Procurement Rate', y='', color = 'Consent Law') + theme(legend.position="top")
```

```{r}
# data labels
p <- ggplot(data = by_country, mapping = aes(x = roads_mean, y = donors_mean))
p + geom_point() + geom_text(mapping = aes(label = country))

# to adjust the position of labels
p <- ggplot(data = by_country, mapping = aes(x = roads_mean, y = donors_mean))
p + geom_point() + geom_text(mapping = aes(label = country), hjust = 0)

# install new package
install.packages('ggrepel')
library(ggrepel)

# use the elections_historic data set
p <- ggplot(elections_historic, aes(x=popular_pct, y=ec_pct, label=winner_label))

p + geom_hline(yintercept=0.5, size=1.4, color='gray80') + 
  geom_vline(xintercept=0.5, size=1.4, color='gray80') +
  geom_point()+
  geom_text_repel() +
  scale_x_continuous(labels = scales::percent) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "winner's share of the popular vote",
  y = "winner's share of electoral college votes",
  title = 'Presidential elections: popular & electoral college margins', subtitle = '1824-2016')
```

