---
title: "class 4"
author: "Yongran Yan"
date: "2023-03-20"
output: html_document
---

```{r}
# to load libraries
library(gapminder)
library(ggplot2)
library(socviz)
library(tidyverse)
library(ggrepel)

# data processing from last class
by_country <- organdata |> 
  group_by(consent_law, country) |> 
  summarize_if(is.numeric, funs(mean, sd), na.rm = TRUE) |> 
  ungroup()

# to label specific points using subset
p <- ggplot(data = by_country, mapping = aes(x = gdp_mean, y = health_mean))
p + geom_point() +
  geom_text_repel(data = subset(by_country, gdp_mean > 25000), mapping = aes(label = country))

# use the annotate() function
# add text to specific position of the graph defined by x and y
p <- ggplot(data = organdata, mapping = aes(x = roads, y = donors))
p + geom_point() + annotate(geom = 'text', x = 91, y = 33, label =
                              'A surprisingly high \n recovery rate.', hjust = 0)

# annotate() can also be used to draw shapes
p <- ggplot(data = organdata, mapping = aes(x = roads, y = donors))
p + geom_point() + 
  annotate(geom = 'rect', xmin = 85, xmax = 135, ymin = 30, ymax = 35, fill = "red", alpha = 0.2) +
  annotate(geom = 'text', x = 91, y = 33, label =
                              'A surprisingly high \n recovery rate.', hjust = 0)
```

```{r}
# work with asasec data set
head(asasec)

# plot scatterplot with smoothed graph
p <- ggplot(data = subset(asasec, Year == 2014), mapping = aes(x = Members, y = Revenues))
p + geom_point() + geom_smooth()

# modify the plot
p <- ggplot(data = subset(asasec, Year == 2014), mapping = aes(x = Members, y = Revenues))
p + geom_point(mapping = aes(color = Journal)) + 
  geom_smooth(method = 'lm')

# to create an intermediate object to add more layers to the plot
p0 <- ggplot(data = subset(asasec, Year == 2014), mapping = aes(x = Members, y = Revenues, label = Sname))

p1 <- p0 + geom_point(mapping = aes(color = Journal)) + 
  geom_smooth(method = 'lm', se = FALSE, color = 'gray80')

p2 <- p1 + geom_text_repel(data = subset(asasec, Year == 2014 & Revenues > 7000), size = 2)

p2

# add labels and titles to p2
p3 <- p2 + labs(x='Membership',
                y='Revenues',
                color='Section has own Journal',
                title='ASA sections',
                subtitle='2014 Calendar Year',
                caption = 'Sources: ASA annual report.')
p4 <- p3 + scale_y_continuous(labels=scales::dollar) +
  theme(legend.position='top')
p4
```
```{r}
# install Rcolorbrewer package
install.packages('RColorBrewer')

library(RColorBrewer)

# to see what colors it has
par(mar=c(3,4,2,2))
display.brewer.all()

# to use colors in the plot
p <- ggplot(data = organdata, mapping = aes(x = roads, y = donors, color = world))
p + geom_point(size = 2) +
  scale_color_brewer(palette = 'Set2') +
  theme(legend.position = 'top')

```

```{r}
# manually choosing colors
cb_palette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
p4 + scale_color_manual(values = cb_palette)
```

```{r}
# use color and text together to highlight certain parts in the plot
# use the county_data data set
head(county_data)

# define blue and red color for Domocratic and Repulican party
party_colors <- c("#2E74C0", "#CB454A")

p0 <- ggplot(data = subset(county_data, flipped == 'No'),
             mapping = aes(x = pop, y = black/100))
p1 <- p0 + geom_point(alpha = 0.15, color ='gray50') +
  scale_x_log10(labels=scales::comma)
p1

# to highlight the counties did flip party
p2 <- p1 + geom_point(data = subset(county_data, flipped == 'Yes'), mapping = aes(x = pop, y = black/100, color = partywinner16)) +
  scale_color_manual(values = party_colors)
p2

# add labels and legends
p3 <- p2 + scale_y_continuous(labels=scales::percent) +
  labs(color = 'County flipped to...',
       x = 'County Population (log scale)',
       y = 'Percent Balck Population',
       title = 'Flipped counties 2016',
       caption = 'Counties in gray did not flip')
p3

p4 <- p3 + geom_text_repel(data = subset(county_data, flipped == 'Yes' & black > 25),
                           mapping = aes(x = pop, y = black/100, label = state), size = 2)
p4 + theme_minimal() + theme(legend.position = 'top')
```

```{r}
# ggplot themes
theme_set(theme_dark())
p4

# to install ggthemes packages
install.packages('ggthemes')
library(ggthemes)

theme_set(theme_economist())
p4
# another way: p4 + theme_economist()

# reset theme back to minimal
theme_set(theme_minimal())
p4
```

