---
title: "class 9"
author: "Yongran Yan"
date: "2023-04-01"
output: html_document
---

Interactive chart
```{r}
# install and load the package
install.packages('rAmCharts')
library(rAmCharts)

# view our data set
head(iris)

# make a dynamic data viz
amPlot(iris, col=c('Sepal.Length', 'Sepal.Width'),
       type = c('line', 'step'),
       zoom = TRUE,
       legend = TRUE)
```

Use ggplot and gganimate to generate interactive plots
```{r}
# install and load packages
install.packages('gganimate')
install.packages('gifski')
library(ggplot2)
library(gapminder)
library(gganimate)
library(gifski)

# use the gapminder data set by ggplot for animation
p <- ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp, size = pop, color = country)) +
  geom_point(show.legend = FALSE, alpha = 0.7) +
  scale_color_viridis_d() +
  scale_size(range = c(2,12)) +
  scale_x_log10() +
  labs(x='GDP per captita',
       y='Life expectancy')
p

# gganimate, trainsition variable is year
p2 <- p + transition_time(year) +
  labs(title = 'Year: {frame_time}')
animate(p2,
        duration = 10,
        renderer = gifski_renderer())
```

Shiny 
```{r}
install.packages('shiny')
library('shiny')
```

