---
title: "class_8"
author: "Yongran Yan"
date: "2023-03-30"
output: html_document
---

```{r}
# load packages
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(tidyverse)
library(socviz)

# review data
election |> select(state, total_vote,
                   r_points, pct_trump, party, census) |>
  sample_n(5)

# to define colors for different parties
party_colors <- c("#2E74C0", "#CB454A") 

# to include all states except for DC and reorder them by 'r_point"
 p0 <- ggplot(data = subset(election, st %nin% "DC"), mapping = aes(x =
 r_points, y = reorder(state, r_points), color = party)) 

 # to plot  
p1 <- p0 + geom_vline(xintercept = 0, color = "gray30") + geom_point(size = 2)
 p2 <- p1 + scale_color_manual(values = party_colors)
p3 <- p2 + scale_x_continuous(breaks = c(-30, -20, -10, 0, 10, 20, 30, 40), labels = c("30\n (Clinton)", "20", "10", "0", "10", "20", "30", "40\n(Trump)"))
p3 + facet_wrap(~ census, ncol=1, scales="free_y") + guides(color=FALSE) + labs(x = "Point Margin", y = "") + theme(axis.text=element_text(size=8))
```
Themetic map of US election data
```{r}
# to install packages
install.packages('maps')
library(maps)

us_states <- map_data('state')
head(us_states)

# make a map
p <- ggplot(data = us_states, mapping = aes(x= long, y = lat, group = group))
p + geom_polygon(fill = 'white', color = 'black')

# make a colorful map
p <- ggplot(data = us_states, mapping = aes(x= long, y = lat, group = group, fill = region))
p + geom_polygon(color = 'gray90', linewidth = 0.1) + 
  coord_map(projection = 'albers', lat0=39, lat1=45) +
  guides(fill = FALSE)

# add data to the map
# to make our 'state' column in lower case
election$region <- tolower(election$state)
us_states_elec <- left_join(us_states, election, by = 'region')
head(us_states_elec)

# plot election data on a map
p0 <- ggplot(data = us_states_elec,
             mapping = aes(x = long,
                           y = lat,
                           group = group,
                           fill = party))
p1 <- p0 + geom_polygon(color = 'gray90', linewidth = 0.1) +
  coord_map(projection = 'albers', lat0 = 39, lat1 = 45)
p2 <- p1 + scale_fill_manual(values = party_colors) +
  labs(title = 'Election Results 2016', fill = NULL)
p2 + theme_map()

# plotting population density
county_map |> sample_n(5)
county_data |>
select(id, name, state, pop_dens) |> sample_n(5)

# merge data sets
county_full <- left_join(county_map, county_data, by = 'id')
head(county_full)

# to plot the county population map
p <- ggplot(data = county_full,
            mapping = aes(x=long,
                          y=lat,
                          fill = pop_dens,
                          group=group))
p1 <- p + geom_polygon(color = 'gray90', size = 0.05) +
  coord_equal()
p2 <- p1 + scale_fill_brewer(palette = 'Blues',
                             labels = c('0-10', '10-50', '50-100','100-500', '500-1000',
                                        '1000-5000', '> 5000'))
p2 + labs(fill = 'Population per \n square mile') +
  theme_map() +
  guides(fill = guide_legend(nrow = 1)) +
  theme(legend.position = 'bottom')
```

Basic flow charts
```{r}
# install packages and load
install.packages('DiagrammeR')
library(DiagrammeR)

# make a basic flow chart
grViz(diagram = "digraph flowchart {
node [fontname = arial, shape = oval, color = blue] 
tab1 [label = '@@1']
tab2 [label = '@@2']
tab3 [label = '@@3']

tab1 -> tab2 -> tab3;
tab2 -> tab4
}

[1]: 'Artefect collection in filed'
[2]: 'Preliminary dating of artefacts (visual)'
[3]: 'Artefects sent to lab for dating' ")

# create another one
grViz(diagram = "digraph flowchart {
      node [fontname = arial, color = pink]
      tab1 [label = '@@1', fontcolor = blue]
      tab2 [label = '@@2', fontcolor = green]
      tab3 [label = '@@3', fontcolor = black]
      tab4 [label = '@@4', fontcolor = red]
      tab5 [label = '@@5', fontcolor = orange]
      
      tab1 -> tab2 -> tab3;
      tab1 -> tab4 -> tab5
}
[1]: 'Cook for dinner?'
[2]: 'Yes'
[3]: 'Go for groceries'
[4]: 'No'
[5]: 'Get Popeyes!' ")
```

